replicaCount: 2

image:
  repository: ghcr.io/shaker5745/sample-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podLabels:
  compliance: "gatekeeper-demo"

ingress:
  enabled: false
